version: '3.8'

services:
  fusionflow:
    image: registry.digitalocean.com/maslow--registry/flowise:1.0.2
    ports:
      - "3000:3000"
    networks:
      - fusionflow_network

  chromaDB:
    image: registry.digitalocean.com/maslow--registry/chroma:latest
    ports:
      - "8000:8000"
    networks:
      - fusionflow_network

networks:
  fusionflow_network:
    driver: bridge
